---
name: Test-Sys-Info
version: 0.17
author:
  - 'Burak Gursoy <burak@cpan.org>'
abstract: Centralized test suite for Sys::Info.
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://bitbucket.org/burak/cpan-test-sys-info/
build_requires:
  Test::More: 0.40
configure_requires:
  Module::Build: 0.35
provides:
  Test::Sys::Info:
    file: lib/Test/Sys/Info.pm
    version: 0.17
  Test::Sys::Info::Driver:
    file: lib/Test/Sys/Info/Driver.pm
    version: 0.17
no_index:
  directory:
    - monolithic_version
    - builder
    - t
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
